services:
  - type: web
    name: sln-app
    env: docker
    plan: free
    autoDeploy: true
    branch: main
    rootDir: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: CI_ENV
        value: production
